# Generated by Django 4.1.7 on 2023-08-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myInvoice', '0003_remove_client_user_alter_add_service_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add_service',
            table='add-services',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
