# Generated by Django 4.1.7 on 2023-08-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myInvoice', '0004_alter_add_service_table_alter_client_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_service',
        ),
    ]
