# Generated by Django 4.1.7 on 2023-08-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myInvoice', '0005_delete_add_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('account', models.IntegerField()),
                ('ifsc', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myInvoice.client')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
